import { getApiConfig } from './config';

export interface CountryCode {
  name: string;
  code: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'United States', code: '+1', flag: '🇺🇸' },
  { name: 'Canada', code: '+1', flag: '🇨🇦' },
  { name: 'China', code: '+86', flag: '🇨🇳' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
  { name: 'Australia', code: '+61', flag: '🇦🇺' },
  { name: 'Germany', code: '+49', flag: '🇩🇪' },
  { name: 'France', code: '+33', flag: '🇫🇷' },
  { name: 'Japan', code: '+81', flag: '🇯🇵' },
  { name: 'India', code: '+91', flag: '🇮🇳' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽' },
];

export const API_CONFIG = {
  get BASE_URL() {
    return getApiConfig().BASE_URL;
  },
  get HEADERS() {
    return getApiConfig().HEADERS;
  },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appName: 'CoRide',
    trips: 'Trips',
    friends: 'Friends',
    garage: 'Garage',
    account: 'Account',
    login: 'Log In',
    loading: 'Loading...',
    register: 'Register',
    logout: 'Log Out',
    createTrip: 'Post Trip',
    startTrip: 'Post Trip',
    joinTrip: 'Add a trip',
    driver: 'DRIVER',
    passenger: 'PASSENGER',
    confirm: 'Confirm',
    cancel: 'Cancel',
    pending: 'Pending',
    matching: 'Matching',
    completed: 'Completed',
    unsettled: 'Unsettled',
    myTrips: 'My Trips',
    pastTrips: 'Past Trips',
    history: 'History',
    inProgress: 'In Progress',
    upcoming: 'Upcoming Trips',
    invitedTrips: 'Invited Trips',
    tripInvitation: 'Trip Invitation',
    vehicleInfo: 'Vehicle Information',
    inviteFriends: 'Invite Friends',
    contactUs: 'Contact Us',
    settings: 'Settings',
    language: 'Language',
    search: 'Search',
    addVehicle: 'Add Vehicle',
    tripDetail: 'Trip Details',
    confirmedBy: 'Confirmed by',
    seatsAvailable: 'seats available',
    modificationAlert: 'Trip modified. Please confirm.',
    next: 'Next',
    previous: 'Previous',
    startLocation: 'Origin',
    endLocation: 'Destination',
    date: 'Date',
    time: 'Time',
    email: 'Email',
    phone: 'Phone Number',
    verificationCode: 'Verification Code',
    sendCode: 'Send Code',
    passwordLogin: 'Password Login',
    phoneLogin: 'Phone Login',
    resetPassword: 'Securely recover your account',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    continue: 'Continue',
    passwordChanged: 'Password successfully reset',
    backToLogin: 'Back to Login',
    emailPlaceholder: 'Enter your email',
    phonePlaceholder: 'Enter phone number',
    startTime: 'Departure',
    timeLeftLabel: 'LEFT',
    driverConfirmed: 'Driver Confirmed',
    driverNotConfirmed: 'Driver Pending',
    passengersConfirmed: 'Confirmed',
    collapseView: 'Collapse View',
    expandView: 'Expand View',
    joinAsPassenger: 'Join as Passenger',
    joinAsDriver: 'Join as Driver',
    driverTBD: 'Driver: TBD',
    acceptInvitation: 'Accept Invitation',
    invitedToDriver: 'invited you to be the driver',
    invitedToGroup: 'invited you to join the group',
    findCarOrPeople: 'Looking for a car or people?',
    findCarOrPeopleSub: 'Select your need to start a convenient carpool journey',
    lookingForPeople: 'Looking for People',
    lookingForPeopleSub: 'I have a car and want to share empty seats',
    lookingForCar: 'Looking for a Car',
    lookingForCarSub: 'I want to find a driver heading the same way',
    initiateTrip: 'Initiate Trip',
    driverModeTag: 'Car finds People',
    passengerModeTag: 'People find Car',
    selectVehicle: 'Select Vehicle',
    optional: 'Optional',
    passengerCount: 'Passenger Count',
    required: 'Required',
    addTimeRange: 'Add Departure Time',
    addDetailedAddress: 'Add detailed address',
    extraOptions: 'Extra Options',
    confirmAndGenerate: 'Confirm and Generate Trip',
    cityDistrictPlaceholder: 'City/District (e.g., Seattle)',
    configureGroup: 'Configure Passenger Group',
    selectGroupMembers: 'Select Group Members',
    groupName: 'Group Name',
    anonymousPassengers: 'Anonymous Passengers',
    me: 'Me',
    alreadyInTrip: 'Already in Trip',
  },
  zh: {
    appName: 'CoRide 拼车',
    trips: '行程',
    friends: '好友',
    garage: '车库',
    account: '账户',
    login: '登录',
    loading: '加载中...',
    register: '立即注册',
    logout: '退出登录',
    createTrip: '发布行程',
    startTrip: '发布行程',
    joinTrip: '添加行程',
    driver: '司机',
    passenger: '乘客',
    confirm: '确认',
    cancel: '取消',
    pending: '待确认',
    matching: '匹配中',
    completed: '已完成',
    unsettled: '未结算',
    myTrips: '我的行程',
    pastTrips: '历史行程',
    history: '历史',
    inProgress: '进行中',
    upcoming: '即将开始',
    invitedTrips: '行程邀请',
    tripInvitation: '收到邀请',
    vehicleInfo: '车辆信息',
    inviteFriends: '邀请好友',
    contactUs: '联系我们',
    settings: '系统设置',
    language: '语言设置',
    search: '搜索',
    addVehicle: '添加车辆',
    tripDetail: '行程详情',
    confirmedBy: '已确认',
    seatsAvailable: '个剩余座位',
    modificationAlert: '行程已修改，请重新确认',
    next: '下一步',
    previous: '上一步',
    startLocation: '起点',
    endLocation: '终点',
    date: '日期',
    time: '时间',
    email: '邮箱',
    phone: '手机号码',
    verificationCode: '验证码',
    sendCode: '发送验证码',
    passwordLogin: '密码登录',
    phoneLogin: '手机登录',
    resetPassword: '安全找回并重置账户',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    continue: '继续',
    passwordChanged: '密码重置成功',
    backToLogin: '返回登录',
    emailPlaceholder: '请输入您的邮箱',
    phonePlaceholder: '请输入手机号',
    startTime: '出发时间',
    timeLeftLabel: '剩余',
    driverConfirmed: '司机已确认',
    driverNotConfirmed: '司机待确认',
    passengersConfirmed: '人已确认',
    collapseView: '折叠视图',
    expandView: '展开视图',
    joinAsPassenger: '加入为乘客',
    joinAsDriver: '加入为司机',
    driverTBD: '司机：待定',
    acceptInvitation: '接受邀请',
    invitedToDriver: '邀请您成为司机',
    invitedToGroup: '邀请您加入小组',
    findCarOrPeople: '找车还是找人？',
    findCarOrPeopleSub: '选择你的需求，开始便捷的拼车之旅',
    lookingForPeople: '找人',
    lookingForPeopleSub: '我有车，想分享空余座位',
    lookingForCar: '找车',
    lookingForCarSub: '我想寻找顺路的司机',
    initiateTrip: '发起行程',
    driverModeTag: '车找人',
    passengerModeTag: '人找车',
    selectVehicle: '选择车辆',
    optional: '可选',
    passengerCount: '乘车人数',
    required: '必填',
    addTimeRange: '添加出发时段',
    addDetailedAddress: '添加详细地址',
    extraOptions: '额外选项',
    confirmAndGenerate: '确认并生成行程',
    cityDistrictPlaceholder: '城市/区域 (例如：Seattle)',
    configureGroup: '配置乘客小组',
    selectGroupMembers: '选择小组成员',
    groupName: '小组名称',
    anonymousPassengers: '匿名乘客',
    me: '本人',
    alreadyInTrip: '已在行程中',
  },
};

export const MOCK_USER: Record<string, unknown> = {
  id: 'user_1',
  userArn: 'user:user_1',
  name: '陈明',
  email: 'chenming@example.com',
  avatar:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuALPOl2sGfmGFNTO0Ixv0OKQPECXUYNSyN35lZ5kmZVavlfsWu5e_-Ab1h2bIarRw3lStkd3eTD1oi1FafHhPVRtzcfP3K-dbwAoGneahk_NL9ssRSD-bwtjhgLxKxBBuXcADqxH7AUTQB1Eglz4dVKeCMZ20u0cjUkoHeHuTqbV4sag5TA-4QkvtkB7DTwyfFtQI8DXB0FG5uy3Mxugu-IU0xFcsLp-ju_zBcamzmpvVe9Mh9Mr920-3zt9NyllFJ1dHcYApevQXU',
  bio: '热爱拼车与旅行的软件工程师。常往返于西雅图与温哥华。',
};

export const MOCK_VEHICLES: Record<string, unknown>[] = [
  {
    id: 'v1',
    brand: 'Tesla',
    model: 'Model 3',
    color: 'White',
    licensePlate: 'CA 8ABC123',
    state: 'California',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCa3t5o3h5SNBUsGdEPcRPoHr0Kabd2M-oc86G6wLfVk-otPcGYyYtZYL4W8O8YPsxCRI7Cky09T2EgilUMxAgkCUs_e8wqPPdi4s8LiciuKIb3cMD6caST7DM_vbS0ZFjKFsgTag4uFRgUoaKFn_Wb0gQ3ayckpz8eSTsmIv9v3gFGdQruglFAZ_lfEdB0ayzFD3X-f61EebSReIH_6_5yLeFxcj4GFwQ1zw8_bvS1eBT3jbkfa-XI7Ma4Qm9XpxGH7hP9ze-FD6Q',
  },
];
